### ISSUE TITLE
[Switch] Failed to open content (chd)

### ISSUE THREAD

**Issue by cucholix** [libretro/4do-libretro#119]
I can start the core see the bios intro, but when attemping to load a chd it goes black screen then a "failed to load content" message appears kicking me back to menu.

Using panafz1.bin in the system folder, tested the same game Alone in the Dark in chd format and it works fine on PC, so it's not a problem with the dump.

**Comment by trapexit** [comment]
Seems that the libnx section is not using the standard build flow as other platforms. Having chd should be the default. @natinusala you're probably the best person to clean it up. Would rather do that vs adding HAVE_CHD to the libnx section explicitly.

**Comment by natinusala** [comment]
Isn't chd support already enabled for all platforms though ? https://github.com/libretro/4do-libretro/blob/master/Makefile#L2

I don't see libnx overriding it, unless I'm missing something?

**Comment by trapexit** [comment]
It is globally set but I've been told chd loading isn't working on Switch. It could be a bug but I don't have the system and it seems to work fine on other platforms.

**Comment by cucholix** [comment]
@natinusala chd is definitely not working on 4DO, it's on other cores like PCE Fast (PCE-CD), GenPlus GX (Sega CD).

**Comment by natinusala** [comment]
Okay so for some reason, the core doesn't use its copy of libretro-common but the one of RetroArch. And guess what, RetroArch wasn't built with `HAVE_CHD` 🤡 

PR : https://github.com/libretro/RetroArch/pull/7922

Now don't party just yet because there is another issue, reading the CHD crashes here : https://github.com/libretro/RetroArch/blob/master/libretro-common/formats/libchdr/libchdr_chd.c#L1674

Here, `chd->codecintf[rawmap[0]]` is NULL so `chd->codecintf[rawmap[0]]->compression` crashes. I can't go further because I don't know the CHD format. Any idea ?

**Comment by trapexit** [comment]
That's odd and shouldn't be. 4DO core has libchdr already embed into the repo and is built against that on other platforms.

https://github.com/libretro/4do-libretro/blob/master/Makefile.common#L138

**Comment by natinusala** [comment]
You use `intfstream_open_chd_track` which is in libretro-common. It's not built inside the core, so it uses RA's.

**Comment by trapexit** [comment]
Yeah, and there is a copy of all that in the 4do repo. It looks like it has to do with the inclusion when compiling statically or not. I'm not familiar with which platforms compile statically and which not but for consistency perhaps the build should always include libretro-common.

**Comment by natinusala** [comment]
¯\_(ツ)_/¯

It fails to read data from the file anyway. I'll try with another CHD in case mine is corrupt.

**Comment by natinusala** [comment]
We took the decision to rewrite the libchdr implementation of libretro-common from upstream to have a working verison of it and fix it once and for all. We'll make sure it works on every platform, including the Switch. It works on Genesis Plus GX so there's no reason why it wouldn't work on 4DO ;)
