### ISSUE TITLE
[Core regression] Cannot load .cue files

### ISSUE THREAD

**Issue by stevenstrike** [libretro/4do-libretro#13]
Loading any .cue files will boot straight to the 3DO bios and show the "Insert CD" screen.
(no errors returned in the log file about this)

Loading .bin is fine though.

(Loading cue files on the non-libretro 4do emulator works)
Windows 10 using latest RA 64 build

**Edit 2017/05/29 : A workaround has been implemented, see @fcatrin  comments.**

**Comment by ofry** [comment]
Now if I rename *.bin to *.iso, it failed to start too (shows the "Insert CD" screen).

So this core is completely broken now :(

**Comment by ofry** [comment]
In 4do 1.3.2.3 all working fine... But I can't use xBRZ scaling in this emulator :(

**Comment by twinaphex** [comment]
Works fine here, I'm going to presume you guys are testing this on Windows again? Guess somebody will have to bisect there, works fine here on Linux.

**Comment by ofry** [comment]
Yes, I use Windows 8 Professional :)

**Comment by ofry** [comment]
Which compiler I should use for building this core? Can I get build tutorial?

**Comment by ofry** [comment]
Log: 

RetroArch [INFO] :: Config: loading config from: C:\retroarch\retroarch.cfg.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: [SoftFilter]: Found plug: 2xBR (2xbr).
RetroArch [INFO] :: [SoftFilter]: Found plug: 2xSaI (2xsai).
RetroArch [INFO] :: [SoftFilter]: Found plug: Blargg NTSC SNES (blargg_ntsc_snes).
RetroArch [INFO] :: [SoftFilter]: Found plug: Darken (darken).
RetroArch [INFO] :: [SoftFilter]: Found plug: EPX (epx).
RetroArch [INFO] :: [SoftFilter]: Found plug: LQ2x (lq2x).
RetroArch [INFO] :: [SoftFilter]: Found plug: Phosphor2x (phosphor2x).
RetroArch [INFO] :: [SoftFilter]: Found plug: Scale2x (scale2x).
RetroArch [INFO] :: [SoftFilter]: Found plug: Super2xSaI (super2xsai).
RetroArch [INFO] :: [SoftFilter]: Found plug: SuperEagle (supereagle).
RetroArch [INFO] :: Using 1 threads for softfilter.
RetroArch [INFO] :: Found shader "C:\retroarch\shaders\retroarch.cgp"
RetroArch [INFO] :: Found shader "C:\retroarch\shaders\retroarch.glslp"
RetroArch [INFO] :: Found shader "C:\retroarch\shaders\xbr_advancedaa.cgp"
RetroArch [INFO] :: Found shader "C:\retroarch\shaders\xbrz.cgp"
RetroArch [INFO] :: Video @ fullscreen
RetroArch [INFO] :: Starting threaded video driver ...
RetroArch [INFO] :: Found GL context: wgl
RetroArch [INFO] :: Detecting screen resolution 1920x1200.
RetroArch [INFO] :: [WGL]: wglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: ATI Technologies Inc., Renderer: AMD Radeon HD 7700 Series.
RetroArch [INFO] :: [GL]: Version: 4.4.12874 Compatibility Profile Context 14.100.0.0.
RetroArch [INFO] :: [GL]: ATI card detected, skipping check for GL_RGB565 support.
RetroArch [INFO] :: Querying GL extension: ARB_sync => exists
RetroArch [INFO] :: Querying GL extension: ARB_texture_float => exists
RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => exists
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_sRGB => exists
RetroArch [INFO] :: GL: Using resolution 1920x1200
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [GL]: Using Cg shader backend.
RetroArch [INFO] :: [Cg]: Vertex profile: arbvp1
RetroArch [INFO] :: [Cg]: Fragment profile: arbfp1
RetroArch [INFO] :: Loading Cg meta-shader: C:\retroarch\shaders\retroarch.cgp
RetroArch [INFO] :: Found #pragma parameter AdvancedAA Input Resolution X (AA_RESOLUTION_X) 0.000000 0.000000 1920.000000 1.000000
RetroArch [INFO] :: Found #pragma parameter AdvancedAA Input Resolution Y (AA_RESOLUTION_Y) 0.000000 0.000000 1920.000000 1.000000
RetroArch [INFO] :: Loading Cg shader: "C:\retroarch\shaders\shaders_cg\xbr\shaders\legacy\5xbr.cg".
RetroArch [INFO] :: Loading Cg shader: "C:\retroarch\shaders\shaders_cg\anti-aliasing\shaders\advanced-aa.cg".
RetroArch [INFO] :: CG: Found semantic "POSITION" in prog #1.
RetroArch [INFO] :: CG: Found semantic "TEXCOORD0" in prog #1.
RetroArch [INFO] :: CG: Found semantic "POSITION" in prog #2.
RetroArch [INFO] :: CG: Found semantic "COLOR" in prog #2.
RetroArch [INFO] :: CG: Found semantic "TEXCOORD0" in prog #2.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 2 program(s).
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_object => exists
RetroArch [INFO] :: [GL]: Creating FBO 0 @ 4096x4096
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {028E} VID:{045E}
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Autodetect: configuration file: (null) score: 2
RetroArch [INFO] :: Autodetect: XInput Controller (User 1) configured in port #0.
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: DirectSound devices:
RetroArch [INFO] :: 	0: ѕервичный звуковой драйвер
RetroArch [INFO] :: 	1: DFX Speakers (DFX Audio Enhancer 11.1)
RetroArch [INFO] :: 	2: »нтерфейс SPDIF (SoundMAX Integrated Digital HD Audio)
RetroArch [INFO] :: 	3: ÷ифровой выход (SoundMAX Integrated Digital HD Audio)
RetroArch [INFO] :: 	4: ƒинамики (SoundMAX Integrated Digital HD Audio)
RetroArch [INFO] :: [DirectSound]: Setting buffer size of 12288 bytes
RetroArch [INFO] :: [DirectSound]: Latency = 64 ms
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Found #pragma parameter AdvancedAA Input Resolution X (AA_RESOLUTION_X) 0.000000 0.000000 1920.000000 1.000000
RetroArch [INFO] :: Found #pragma parameter AdvancedAA Input Resolution Y (AA_RESOLUTION_Y) 0.000000 0.000000 1920.000000 1.000000
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: null: [C:\retroarch\content_history.lpl].
RetroArch [INFO] :: Using content: C:\Users\ofry\Downloads\3DO\death keep, advanced dungeons & dragons (u).CUE.
RetroArch [INFO] :: arg #0: retroarch
RetroArch [INFO] :: arg #1: C:\Users\ofry\Downloads\3DO\death keep, advanced dungeons & dragons (u).CUE
RetroArch [INFO] :: arg #2: -c
RetroArch [INFO] :: arg #3: C:\retroarch\retroarch.cfg
RetroArch [INFO] :: arg #4: -L
RetroArch [INFO] :: arg #5: C:\retroarch\cores\4do_libretro.dll
RetroArch [INFO] :: arg #6: -v
RetroArch [INFO] :: CG: Destroying programs.
RetroArch [INFO] :: CG: Destroying context.
RetroArch [INFO] :: Threaded video stats: Frames pushed: 223, Frames dropped: 0.
RetroArch [INFO] :: Monitor FPS estimation is disabled for threaded video.
RetroArch [INFO] :: === Build =======================================RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 Built: Sep 28 2015
RetroArch [INFO] :: Version: 1.2.2
RetroArch [INFO] :: Git: bbc5bc9
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: Loading dynamic libretro core from: "C:\retroarch\cores\4do_libretro.dll"
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [INFO] :: Environ PERFORMANCE_LEVEL: 5.
RetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: XRGB8888.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] :: 	RetroPad, User 1, Button "B (bottom)" => "B"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Y (left)" => "A"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Select" => "X (Stop)"
RetroArch [INFO] :: 	RetroPad, User 1, Button "Start" => "P (Play/Pause)"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 1, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 1, Button "A (right)" => "C"
RetroArch [INFO] :: 	RetroPad, User 1, Button "L" => "L"
RetroArch [INFO] :: 	RetroPad, User 1, Button "R" => "R"
RetroArch [INFO] :: 	RetroPad, User 2, Button "B (bottom)" => "B"
RetroArch [INFO] :: 	RetroPad, User 2, Button "Y (left)" => "A"
RetroArch [INFO] :: 	RetroPad, User 2, Button "Select" => "X (Stop)"
RetroArch [INFO] :: 	RetroPad, User 2, Button "Start" => "P (Play/Pause)"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Up" => "D-Pad Up"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Down" => "D-Pad Down"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Left" => "D-Pad Left"
RetroArch [INFO] :: 	RetroPad, User 2, Button "D-Pad Right" => "D-Pad Right"
RetroArch [INFO] :: 	RetroPad, User 2, Button "A (right)" => "C"
RetroArch [INFO] :: 	RetroPad, User 2, Button "L" => "L"
RetroArch [INFO] :: 	RetroPad, User 2, Button "R" => "R"
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "C:\retroarch\content\bios".
RetroArch [INFO] :: Environ GET_VARIABLE 4do_high_resolution:
RetroArch [INFO] :: 	enabled
RetroArch [INFO] :: Skipping SRAM load..
RetroArch [INFO] :: Set audio input rate to: 44063.25 Hz.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: [SoftFilter]: Found plug: 2xBR (2xbr).
RetroArch [INFO] :: [SoftFilter]: Found plug: 2xSaI (2xsai).
RetroArch [INFO] :: [SoftFilter]: Found plug: Blargg NTSC SNES (blargg_ntsc_snes).
RetroArch [INFO] :: [SoftFilter]: Found plug: Darken (darken).
RetroArch [INFO] :: [SoftFilter]: Found plug: EPX (epx).
RetroArch [INFO] :: [SoftFilter]: Found plug: LQ2x (lq2x).
RetroArch [INFO] :: [SoftFilter]: Found plug: Phosphor2x (phosphor2x).
RetroArch [INFO] :: [SoftFilter]: Found plug: Scale2x (scale2x).
RetroArch [INFO] :: [SoftFilter]: Found plug: Super2xSaI (super2xsai).
RetroArch [INFO] :: [SoftFilter]: Found plug: SuperEagle (supereagle).
RetroArch [INFO] :: Using 1 threads for softfilter.
RetroArch [INFO] :: Found shader "C:\retroarch\shaders\retroarch.cgp"
RetroArch [INFO] :: Found shader "C:\retroarch\shaders\retroarch.glslp"
RetroArch [INFO] :: Found shader "C:\retroarch\shaders\xbr_advancedaa.cgp"
RetroArch [INFO] :: Found shader "C:\retroarch\shaders\xbrz.cgp"
RetroArch [INFO] :: Video @ fullscreen
RetroArch [INFO] :: Starting threaded video driver ...
RetroArch [INFO] :: Found GL context: wgl
RetroArch [INFO] :: Detecting screen resolution 1920x1200.
RetroArch [INFO] :: [WGL]: wglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: ATI Technologies Inc., Renderer: AMD Radeon HD 7700 Series.
RetroArch [INFO] :: [GL]: Version: 4.4.12874 Compatibility Profile Context 14.100.0.0.
RetroArch [INFO] :: [GL]: ATI card detected, skipping check for GL_RGB565 support.
RetroArch [INFO] :: Querying GL extension: ARB_sync => exists
RetroArch [INFO] :: Querying GL extension: ARB_texture_float => exists
RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => exists
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_sRGB => exists
RetroArch [INFO] :: GL: Using resolution 1920x1200
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [GL]: Using Cg shader backend.
RetroArch [INFO] :: [Cg]: Vertex profile: arbvp1
RetroArch [INFO] :: [Cg]: Fragment profile: arbfp1
RetroArch [INFO] :: Loading Cg meta-shader: C:\retroarch\shaders\retroarch.cgp
RetroArch [INFO] :: Found #pragma parameter AdvancedAA Input Resolution X (AA_RESOLUTION_X) 0.000000 0.000000 1920.000000 1.000000
RetroArch [INFO] :: Found #pragma parameter AdvancedAA Input Resolution Y (AA_RESOLUTION_Y) 0.000000 0.000000 1920.000000 1.000000
RetroArch [INFO] :: Loading Cg shader: "C:\retroarch\shaders\shaders_cg\xbr\shaders\legacy\5xbr.cg".
RetroArch [INFO] :: Loading Cg shader: "C:\retroarch\shaders\shaders_cg\anti-aliasing\shaders\advanced-aa.cg".
RetroArch [INFO] :: CG: Found semantic "POSITION" in prog #1.
RetroArch [INFO] :: CG: Found semantic "TEXCOORD0" in prog #1.
RetroArch [INFO] :: CG: Found semantic "POSITION" in prog #2.
RetroArch [INFO] :: CG: Found semantic "COLOR" in prog #2.
RetroArch [INFO] :: CG: Found semantic "TEXCOORD0" in prog #2.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 2 program(s).
RetroAdisc size: 842216754 sectors
disc size: 842216754 sectors
rch [INFO] :: Querying GL extension: ARB_framebuffer_object => exists
RetroArch [INFO] :: [GL]: Creating FBO 0 @ 8192x8192
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {028E} VID:{045E}
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Autodetect: configuration file: (null) score: 2
RetroArch [INFO] :: Autodetect: XInput Controller (User 1) configured in port #0.
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: DirectSound devices:
RetroArch [INFO] :: 	0: ѕервичный звуковой драйвер
RetroArch [INFO] :: 	1: DFX Speakers (DFX Audio Enhancer 11.1)
RetroArch [INFO] :: 	2: »нтерфейс SPDIF (SoundMAX Integrated Digital HD Audio)
RetroArch [INFO] :: 	3: ÷ифровой выход (SoundMAX Integrated Digital HD Audio)
RetroArch [INFO] :: 	4: ƒинамики (SoundMAX Integrated Digital HD Audio)
RetroArch [INFO] :: [DirectSound]: Setting buffer size of 12288 bytes
RetroArch [INFO] :: [DirectSound]: Latency = 64 ms
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Found #pragma parameter AdvancedAA Input Resolution X (AA_RESOLUTION_X) 0.000000 0.000000 1920.000000 1.000000
RetroArch [INFO] :: Found #pragma parameter AdvancedAA Input Resolution Y (AA_RESOLUTION_Y) 0.000000 0.000000 1920.000000 1.000000
RetroArch [INFO] :: null: [C:\retroarch\content_history.lpl].
RetroArch [INFO] :: Environ (Private) EXEC.
RetroArch [INFO] :: Saving config at path: "C:\retroarch\retroarch.cfg"
RetroArch [INFO] :: Saving RAM type #0 to "C:\Users\ofry\Downloads\3DO\death keep, advanced dungeons & dragons (u).srm".
RetroArch [INFO] :: Saved successfully to "C:\Users\ofry\Downloads\3DO\death keep, advanced dungeons & dragons (u).srm".
RetroArch [INFO] :: Saving RAM type #1 to "C:\Users\ofry\Downloads\3DO\death keep, advanced dungeons & dragons (u).rtc".
RetroArch [INFO] :: Average audio buffer saturation: 4.39 %, standard deviation (percentage points): 8.54 %.
RetroArch [INFO] :: Amount of time spent close to underrun: 97.59 %. Close to blocking: 0.00 %.
RetroArch [INFO] :: CG: Destroying programs.
RetroArch [INFO] :: CG: Destroying context.
RetroArch [INFO] :: Threaded video stats: Frames pushed: 1160, Frames dropped: 7.
RetroArch [INFO] :: Monitor FPS estimation is disabled for threaded video.
RetroArch [INFO] :: [PERF]: Performance counters (RetroArch):
RetroArch [INFO] :: [PERF]: Avg (softfilter_process): 27688135 ticks, 1390 runs.
RetroArch [INFO] :: [PERF]: Avg (thr_frame): 13782856 ticks, 1390 runs.
RetroArch [INFO] :: [PERF]: Avg (frame_run): 14439850 ticks, 1383 runs.
RetroArch [INFO] :: [PERF]: Avg (copy_frame): 5831070 ticks, 1383 runs.
RetroArch [INFO] :: [PERF]: Avg (audio_convert_s16): 8116 ticks, 1704 runs.
RetroArch [INFO] :: [PERF]: Avg (audio_dsp): 22335 ticks, 1704 runs.
RetroArch [INFO] :: [PERF]: Avg (resampler_proc): 94073 ticks, 1704 runs.
RetroArch [INFO] :: [PERF]: Avg (audio_convert_float): 3987 ticks, 1704 runs.
RetroArch [INFO] :: Average audio buffer saturation: 4.39 %, standard deviation (percentage points): 8.54 %.
RetroArch [INFO] :: Amount of time spent close to underrun: 97.59 %. Close to blocking: 0.00 %.
RetroArch [INFO] :: Monitor FPS estimation is disabled for threaded video.

**Comment by ofry** [comment]
When I convert *.cue-*.bin pair to *.iso by WinISO http://www.winiso.com/
game was started.

**Comment by nitro322** [comment]
Confirming this.  Have a redump-verified image of Road Rash in bin/cue format.  No matter how I try to load it, I simply get the default 3DO bios prompting me to Insert Disc.  However, if I use bchunk to convert the BIN file to an ISO, I can load that perfectly.

This is under Linux (Gentoo amd64) w/ RetroArch 1.5.0 and 4DO core 1.3.2.4.

Understand you need to prioritize, but it would be nice to get this resolved.  I prefer to keep my images in BIN/CUE format so I can validate against redump.org.

Thanks for your work on this.  As far as I'm aware this is the only functional 3DO emulator on Linux, so even as-is it's a real treat.  :-)

**Comment by fcatrin** [comment]
I've just added a pull request to support MODE1/2352 images (with a .CUE file) 

https://github.com/libretro/4do-libretro/pull/26

**Comment by nitro322** [comment]
That's fantastic.  Thanks!

I just played around with the latest build (since twinaphex was so quick to merge) and can confirm the following:

1. Loading retroarch by directly specifying the BIN file of a BIN/CUE pair works
2. Loading retroarch by directly specifying the CUE file of a BIN/CUE pair fails

Judging from the comments in your commit, that appears intentional, correct?  May I ask why?  Most other systems/emulators I've messed with tend to accept CUE files instead of, or sometimes in addition to, the BIN file.  In terms of consistency it seems like that'd be desired here as well, but maybe you have a technical reason for not supporting it?

Either way, I appreciate the work you put into this.  Thanks a bunch.

**Comment by fcatrin** [comment]
Yes, it is intentional. It was for simplicity:
Some games are distributed as ISO with no CUE file, and some others are distributed as ISO with a CUE file. In the latter case, I don't know if the game may be detected as two games or not, because both files would be accepted as valid media.
Also, accepting CUE files would require more parsing just to get the file name of the image file. So I thought that it will be easier to accept image files with an optional CUE file.

**Comment by ofry** [comment]
But in that way I can't load CUE+BIN game from retroarch interface.

If I select BIN, suggested cores haven't 4DO.
If I select CUE, I go into BIOS.

So please do accept CUE, if valid BIN presents in CUE path.

**Comment by ofry** [comment]
> In the latter case, I don't know if the game may be detected as two games or not, because both files would be accepted as valid media.

About this: I don't know is 3do game scan works... (it will libretro-database issue then). But in PSX games (redump format) only CUE's has added to playlist if I scan directory from RA.

**Comment by fcatrin** [comment]
The problem with 3DO is that not all files have "CUE" files, so if you require a CUE files those games will not be added.  If you require BIN _and_ CUE files, may be both will be added (I cannot confirm that).

May be the suggested cores feature is using the info contained in the .INFO file for that core. That should be updated:

Currently the 4do_libretro.info file has:
supported_extensions = "iso|cue"

It should be:
supported_extensions = "iso|bin|img"

Can you try updating that file?

**Comment by ofry** [comment]
I don't understand it.

If load CUE file, but BIN file doesn't present... for example, Beetle PSX will simply "fail to load content".

About db scan: I will try this feature.

**Comment by ofry** [comment]
3do games scan DON'T working, so this is shouldn't be a problem.

```
RetroArch [INFO] :: Parsing CUE file 'C:\Users\ofry\Downloads\3DO\lucienne's quest (u)\Lucienne's Quest (U).cue'...
RetroArch [INFO] :: Found first data track on file 'C:\Users\ofry\Downloads\3DO\lucienne's quest (u)\Lucienne's Quest (U).BIN+0'
RetroArch [INFO] :: Reading first data track...
RetroArch [INFO] :: Comparing with known magic numbers...
RetroArch [INFO] :: Could not find compatible system.
```

**Comment by fcatrin** [comment]
"If load CUE file, but BIN file doesn't present... "
That case will never work, because the BIN file is the CD image, the CUE file is just a descriptor for the BIN file. If you have a CUE file without a BIN file, you don't have a CD image to work with.

3DO will not open CUE files. It didn't do it before and with the new patch it won't do it.
To understand the issue forget about the CUE file for a minute. The original code assumed that all CD images have 2048 bytes per sector. Everything different didn't work.
The new version will first try to find a CUE file for additional information about the number of bytes per sector, the cue file will make it use 2048 or 2352 bytes per sector.  If there is no cue file, the new version will try to guess dividing the image file size by 2048 and 2352, it will use the size that fits perfect with that sector size.

As you can see, apart from getting that number, the cue file is useless.  Other systems like playstation and dreamcast require to use the cue file to support CD-Audio, that's why they always will have a cue file.

From your last post, I guess that RetroArch is trying to parse a CUE file, but as I said, some games don't have a CUE file so it cannot be mandatory.  You have to pass a BIN, ISO or IMG file and the core will make the rest.  The .info file should be updated to remove the CUE extension from the list.

**Comment by ofry** [comment]
Maybe it's useless, I don't argue with it.

But why don't just parse BIN or IMG or ISO file from CUE? Little feature request :)

**Comment by ofry** [comment]
Standalone 4DO opens CUE file normally...

**Comment by fcatrin** [comment]
it can be done only that I cannot do it right now.  In the meanwhile, all non working games should load fine with this new version.

**Comment by stevenstrike** [comment]
OK for the workaround, but i'd like to keep this issue open as long as the proper regression isn't fixed.

**Comment by fcatrin** [comment]
Due to popular request, I've updated the patch to include CUE file support instead of CD Images only.
https://github.com/libretro/4do-libretro/pull/28

**Comment by ofry** [comment]
Yes, it's working. Thanks.

Issue can be closed, I think.

**Comment by mccorkled** [comment]
I realize this is old, but I am getting this error on Beetle PSX HW when dragging a cue in.

**Comment by hizzlekizzle** [comment]
This repo is for 4do-libretro issues only. If Beetle-PSX is having issues with cue sheets, you should open an issue over in its repo.

**Comment by mccorkled** [comment]
I apologize. A Google search led me here. I was unaware that there were different repos for different cores.
