### ISSUE TITLE
Random freezing during games on Odroid XU4 & N2

### ISSUE THREAD

**Issue by Cee123** [libretro/4do-libretro#133]
After about 10-20 minutes of play into just about 3DO game on the Odroid XU4 and N2, the game just freezes. It happens often with
-Captain Quazar
-Gex
-PO'ed
-Road Rash
-Crash 'n Burn
-Corpse Killer
-As well as several others

More information - all of these files are CHD format. I'm using The Retro Arena, latest version, with 4DO installed from source.

I've tried both bioses, panafz1.bin and panafz10.bin.

Not really sure what's going on there.

**Comment by trapexit** [comment]
Is the system freezing or retroarch / 4do?

**Comment by trapexit** [comment]
What are your settings? Can leaving say, Road Rash, in attract mode for 10+ minutes trigger it?

**Comment by Cee123** [comment]
Ah sorry, I should've been more specific. My bad. It seems to just freeze on 4DO, but the retroarch menu etc is still useable. Which is strange.

**Comment by Cee123** [comment]
Interesting, I had not checked that setting. I'll check if that setting is turned on or off. Maybe it's on by default.

**Comment by Cee123** [comment]
I don't think it's to do with attract mode (not quite sure what that is)

Settings I have under options
Bios: Panasonic fz-10
Font: off
CPU overclock: 1.0x
Threaded DSP: on
High resolution: off
Nvram storage: per game
Active devices: 1
Madam matrix engine: hardware

Under video settings
Threaded video: on
Vsync: on
Hard GPU sync: off
Bilinear filtering: on
Aspect ratio: core provided
The rest of the settings are pretty much default

**Comment by trapexit** [comment]
Turn off Threaded DSP and recheck please.

**Comment by Cee123** [comment]
> 
> 
> "attract mode" is just a general term for the demo that a game runs (like an arcade game showing game play and an intro over and over).

Aha, yeah it does do that. It does freeze during the attract mode sometimes for different games.

**Comment by Cee123** [comment]
> 
> 
> Turn off Threaded DSP and recheck please.

Alright, will try that and see if it works. Thanks!

**Comment by Cee123** [comment]
Awesome thanks! You're a legend. So far so good. Seems to be that the threaded DSP was causing the problem.

**Comment by Cee123** [comment]
You were right. It was the threaded DSP that was causing it to freeze randomly.

**Comment by Cee123** [comment]
Oh OK. Interesting. Sounds like a pretty big task to do a rewrite. Yeah I had turned that setting off altogether and suddenly everything now seems to be running better than what it was before.
