### ISSUE TITLE
Latest Update Crashes

### ISSUE THREAD

**Issue by xiaNaix** [libretro/4do-libretro#15]
Windows 10 x64.  Latest update of the 4DO core (August 24th) crashes when loading an iso and goes back to desktop.  I re-installed an older version of the core (August 15) and everything works fine.

**Comment by twinaphex** [comment]
This should fix it -

https://github.com/libretro/4do-libretro/commit/a23e79bf82e08dc3312b98ba2b442364be5cfcc5
