### ISSUE TITLE
SRAM space bug

### ISSUE THREAD

**Issue by sniperpon** [libretro/4do-libretro#17]
Steps to reproduce:
1. Load an .iso for "Soccer Kid"
2. Beat the first set of stages, then save; a .srm file will be created
3. Quit retroarch
4. Restart retroarch, and load the "Soccer Kid" .iso
5. The game will prompt with its "there will not be enough free space to store the saved games and the high score table" message. See attached screenshot

The .srm file is 32k, which I think is the size of the 3DO's storage. But it's almost like there is an emulation bug where the game itself is somehow filling the entire 32k, or something along those lines.

![screenshot from 2016-06-03 08-57-59](https://cloud.githubusercontent.com/assets/11429394/15781134/5016f9ba-296a-11e6-866f-5a08f05c69ab.png)

**Comment by trapexit** [comment]
@sniperpon I found a small bug in the initialization of the NVRAM which some games seemed to ignore and others had issues with. My patch fixed that but I didn't get a chance to test Soccer Kid. Please try building master of 4do-libretro (or contact me and I can give you the .so if you're on Linux) and test it out. If it still happens after this patch please reopen this ticket and I'll take a closer look.
