### ISSUE TITLE
[feature request] CUE+BIN support

### ISSUE THREAD

**Issue by ofry** [libretro/4do-libretro#24]
I mean CUE + BIN, where CUE file like that:

```
FILE "Lucienne's Quest (U).BIN" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
```

This is work fine with standalone 4do 1.3.2.4.

**Comment by nitro322** [comment]
This is related to (dupe?) bug 13.  Agree that it would be nice to get this fixed, but as a workaround you can use bchunk, bin2iso, winiso or the like to convert the bin/cue to iso and load that.

**Comment by ofry** [comment]
#13 This issue solved.

Issue can be closed, I think.
