### ISSUE TITLE
Cannot play (control) Super Wing Commander

### ISSUE THREAD

**Issue by nitro322** [libretro/4do-libretro#25]
Gamepad control is completely unresponsive in Super Wing Commander.  Button inputs appear to be unrecognized, such that it's impossible to even start a game.  This appears to be the same issue described in 4DO's compatibility list (http://wiki.fourdo.com/Compatibility_List#Super_Wing_Commander):

"Version 1.1.5.0 fixed a bug where the controls are non-responsive. This was happening because all 6 controllers were being emulated all the time. Starting with this version, only emulated controllers that have bindings will be connected to the emulated console. Having Bindings on 6 controllers will cause the controls to stop working again though."

It should supposedly be fixed as of version 1.1.5.0, though.  I tried setting the input device type for all but the first player to None, but that didn't seem to have any effect.  Don't know what else to try.

**Comment by neuromancer** [comment]
This is still is still an issue in last revision (12eba56e3ddb1cd3c53bf26f62adeca7cc0389af). :cry:

**Comment by trapexit** [comment]
I got a fix. Need to figure out the best way to enable it. I'll have something in the next day or so.

**Comment by neuromancer** [comment]
Super Wing Commander is playable now. Thanks a lot!

**Comment by nitro322** [comment]
Hello.  Apologies for the really late reply here, but I just got a chance to try out Super Wing Commander with those memory leak and input handling bug fixes applied, but I'm still having the same problem with the game not seeming to accept any input.  Is there some trick or new config option that I need to set in order to make this work?

I'm running 1.7.3 - 4DO 1.3.2.4 ae84c82.

Just FYI, I was also affected by the Crash n. Burn boot loop bug you fixed a few months ago.  Found the new hack option for that in the configuration settings, and once applying that the game works great.  So, I'm confident my gamepad is working properly with retroarch and 4do-libretro.

**Comment by trapexit** [comment]
Did you set the number of active devices to 1?

**Comment by nitro322** [comment]
well, yeah.  Apologies, I don't think my last statement came across clear.  I *do* have User 1 Device set to a joypad.  All of the other controllers are set to None.  This is the same configuration that I was using in Crash 'n Burn (minus the timing hack) and other games, which all work fine.

**Comment by trapexit** [comment]
Sorry, I misread the statement.

It was definitely working hence my closing the ticket but maybe it broken again. Something is weird with that game.

**Comment by nitro322** [comment]
Thanks.  Would it help if I provide my configuration, or any kind of debug output?  Maybe I have something else set that's conflicting with this.  I'm at work right now, but would be happy to provide anything that might help later tonight.

**Comment by nitro322** [comment]
well that was fast.  :-)  I'll be able to confirm this tonight.

Thanks!

**Comment by trapexit** [comment]
No problem. And I'm hoping to figure out the flightstick soon so you'll be able to use analog controls in SWC and other games that support it.

**Comment by nitro322** [comment]
Working great now!  Thanks again for the super quick response, and for all your work on this in general.  3do was one of the last big systems that I'd been unable to experience either through hardware or emulation (on Linux), so it's really nice to be able to check out these game now.
