### ISSUE TITLE
Graphics tearing

### ISSUE THREAD

**Issue by alegag** [libretro/4do-libretro#29]
This graphic bug has been introduced in commit 48323f12c52232effbacc38b9b890ecacd51d290

Observable in Out of this World, right at the beginning.

From commit 3ff1358 the result was:
![okay](https://cloud.githubusercontent.com/assets/21232519/26763048/2f27047c-491a-11e7-941b-c54a8f9c8727.jpg)

From commit 48323f12c52232effbacc38b9b890ecacd51d290 and up-to last commit, the result is:
![notokay](https://cloud.githubusercontent.com/assets/21232519/26763056/437114b8-491a-11e7-8ae1-763422412f2e.jpg)

Tested on a ARMv7 (Odroid XU-4 exactly).

**Comment by alegag** [comment]
I isolated the problem to this file: libfreedo/Madam.c

**Comment by alegag** [comment]
Now that PR has been merged, just to be sure, did a pull on master and recompiled.

Now, the result is looking a little bit better !
![now](https://cloud.githubusercontent.com/assets/21232519/26764108/838f6310-492e-11e7-9880-0783308444b0.jpg)

Issue can be closed !

**Comment by twinaphex** [comment]
Yeah, I still get some tearing in Super Street Fighter II Turbo, but maybe that game just has implicit tearing by default?

Somebody should probably test it on a real 3DO one of these days, but yeah, I wouldn't doubt that very few 3DO games had smooth scrolling. Gex seems to have really jerky scrolling but I bet that is just the 3DO version's fault.

**Comment by alegag** [comment]
I could test those two on my real 3DO.  I'll try to do this in the next few days and update you.  In the meantime, if you want to send me a screenshot of those tearings so I can compare with the real hardware, we could document that.

Maybe we should open a different issue tho' as this one was more related to a regression that to tweaks.

I don't think I'm the person able enough to help with the code at that level tho' (or not having time enough to do so), but documenting is one step in the right direction I think ;-)

**Comment by twinaphex** [comment]
Yeah, it'd be interesting to know either way if the SSF2T port on 3DO had implicit tearing. I think it does but i could be wrong.
