### ISSUE TITLE
Add CHD support to 4DO [Bounty]

### ISSUE THREAD

**Issue by ajshell1** [libretro/4do-libretro#34]
This is a follow-up to a previous bounty.

All I ask is that someone adds CHD support to the 4DO

The bounty will be $15.

I realize that the 3DO isn't the most popular console, but I thought I might as well make this bounty to cover the last RetroArch core that uses compact discs (excluding PicoDrive, which I might make a bounty for later).

**Comment by Gravel22** [comment]
I too want chd support for the 3do. Thanks a lot for whoever can make this!

**Comment by twinaphex** [comment]
Alright @ajshell1, was there a bounty allocated to this?

**Comment by ajshell1** [comment]
Yes.

**Comment by twinaphex** [comment]
Can you link to it please? That way, the bounty could go towards trapexit.

**Comment by trapexit** [comment]
I wasn't able to find anything about a bounty for this outside this thread. Let's not worry about it. If individuals wish to support what I'm doing they can so via [these means](https://github.com/trapexit/mergerfs#support-development).
