### ISSUE TITLE
general code cleanup

### ISSUE THREAD

**Issue by trapexit** [libretro/4do-libretro#38]
The FreeDO / 4DO code is kind of a mess. Both in structure and layout. Would anyone mind a general cleanup? It could make porting misc changes over more difficult but given the apparent abandonment of the original projects this should be less of an issue and would help long term maintenance.

**Comment by twinaphex** [comment]
I don't mind this, as long as we keep it C-based and at least ensure C89 backwards compatibility.

**Comment by trapexit** [comment]
I spoke with the 4DO project lead and he is supportive of my efforts. I've a question regarding my cleanup. Would you rather me do one file / interface at a time and submit PRs for each of them or do the whole thing in one go?

**Comment by twinaphex** [comment]
I've given you direct commit access now, I don't know how much validation you need from me but generally I am willing for you to take the lead in this and I'll just go along with most of your design considerations. If at any point in time there are any real problems that require me to talk to you about changing some stuff, I believe these can be easily worked out.

I am generally easy to work with, and I don't really have any big lines in the sand except for just basic portability considerations like making sure the core keeps working on the currently existing platforms, etc. But that's about it. That and if the core were to be made unnecessarily much slower than it is right now and there would be no way to get the lost performance back through some kind of core option, that would be another point of contention, but other than that, everything's fair game.

So whichever way works best for you is fine with me. If you prefer to do it all in one go, go ahead. If you prefer the other way ,we can do it like that.

**Comment by trapexit** [comment]
My intent is to make it more portable and improve performance so shouldn't be any issues there. 

How is platform compatibility managed currently? I wouldn't image everyone is building on every platform.

**Comment by twinaphex** [comment]
You can see 4DO being compiled for every platform in real-time on one of our Discord channels on Libretro. #buildbot is the channel name. It's also available for viewing on IRC on Freenode, except there it's known as #libretro-buildbots.
