### ISSUE TITLE
Crash & Burn DEMO reboot issue

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/4do-libretro#57]
Crash & Burn still has the infinite demo loop bug in the latest version of the core. You can’t access the main game because it keeps rebooting at the same demo once you press a button.

Edit: Sorry for the close/re-open i was trying to edit my post

**Comment by trapexit** [comment]
Just to confirm... you've enabled the relevant hack option?

**Comment by Tasosgemah** [comment]
Huh, i wasn't aware that it was an option i have to enable. Of course now that i did this the game is fixed.

Thanks and sorry for the false alarm.
