### ISSUE TITLE
Help Wanted: Russian to English translation of 3DOessence documentation

### ISSUE THREAD

**Issue by trapexit** [libretro/4do-libretro#58]
https://github.com/trapexit/3DO-information/tree/master/hardware/memory%20mappings

Looking for someone who's fluent in Russian, English, and technical to help translation of the 3DOessence.xml spreadsheet.

The file in the linked repo was translated using Google Translate but it leaves a lot to be desired.

**Comment by descent-ru** [comment]
Here's a preliminary translation of the 1st sheet. I'll try to have the rest done by Sunday. There are some things I don't understand, but that'll wait 'till tomorrow. Nighty night.

[3DO Memory Map Eng (WIP).ods.zip](https://github.com/libretro/4do-libretro/files/1905156/3DO.Memory.Map.Eng.WIP.ods.zip)

**Comment by descent-ru** [comment]
Halfway there! This is surprisingly draining, so I hope to sort this out tomorrow.

Meanwhile, here are some Russian 3DO resources you may've missed:

http://web.archive.org/web/20071208170914/http://thdo-homebrew.narod.ru/3do_dev_tools.htm
http://altmer.arts-union.ru/3DO/docs.htm
http://develop3do.narod.ru/

Because who doesn't want from datashits?

[3DO Memory Map Eng (WIP).ods.zip](https://github.com/libretro/4do-libretro/files/1908836/3DO.Memory.Map.Eng.WIP.ods.zip)

**Comment by trapexit** [comment]
Thank you so much. It's really appreciated.

Thanks for the links. I'm pretty sure I've come across them. I do have some other patents to upload to this repo I just want to rename them first so it's easier to find things. I'll double check these though to confirm I got everything.

**Comment by descent-ru** [comment]
No problem at all. Though I don't play games much, I still appreciate the work you and the others are doing. I'm taking on a big project on Monday, so I'll be unavailable for a long time. If you have any more Russian documents to translate then do post them here so I'll do what I can.

**Comment by descent-ru** [comment]
A-a-and done.

[3DO Memory Map Eng (Final).ods.zip](https://github.com/libretro/4do-libretro/files/1910529/3DO.Memory.Map.Eng.Final.ods.zip)

Some notes on translation.

I've done some improvements on the layout and wording, so it's not a verbatim tl. I took extra care to be extra careful doing it, but some errors may've crept in. It's not worth consulting the original over it anyway. Wherever the original wording wasn't clear I marked with (unsure). The translation took me about 10 hours. The offer to translate something else stands for a day or so, then I'll go off grid for the next year.

The original author seems to be Altmer, the author of the Phoenix 3DO emu and, more recently, it's Android port. His 3DO site, arts-union.ru, has been abandoned for years. He himself has expressed a strong desire to have nothing more with 3DO emulation (he had a few articles on habrahabr, the Russian IT community), citing 3DO emulation as being good enough already. His most recent work is an Atari Jaguar emulator, there's a highly technical article on habrahabr.

Hope this helps,
D.

**Comment by trapexit** [comment]
I don't have anything else. Thank you again for helping out. It's really appreciated. I reached out to Altmer and either due to his disinterest in 3DO emulation, the language barrier, or whatever he seemed disinterested in helping out directly or indirectly. He did indicate that he may someday be willing to open source his work.

Good luck with your project.
