### ISSUE TITLE
Lost Eden stall/crash on first loading screen picture

### ISSUE THREAD

**Issue by thorias** [libretro/4do-libretro#63]
Hi,

Lost Eden stall/crash on the first loading screen picture, I tried with different isos and leaving it running for 30 min it doesn't load and stall there.

**Comment by trapexit** [comment]
Unfortunately the 4DO compatibility list indicates a much earlier release worked and I imagine a decent amount changed between 1.2.0.3 and 1.3.2.4 (which this is based on). Might be difficult to track down when it stopped working.

If you could try running it via older versions of the original 4DO emulator it'd greatly help narrow it down. https://sourceforge.net/projects/fourdo/files/

**Comment by thorias** [comment]
Hi Trapexit,

Yeah understand, I'll give a try with earlier 4DO releases and see how it goes and update my findings there.

Thanks for the follow up, greatly appreciated!

**Comment by thorias** [comment]
Hello Trapexit,

I just tested it on 4DO 1.3.2.4 on Windows, it takes about 1min 8s to load from the main screen and works fine after that, I tried it again in 4DO/retroarch but still stand on the first loading screen...I left it for more than 10mins but it's a no go...So seems it is an issue with the libretro/retroarch core...If you can try it from your side...

Thank you!

**Comment by thorias** [comment]
Hello Trapexit,

With the latest release of 4DO core it works now!
Great job!

Thanks!
