### ISSUE TITLE
Vsync not working.

### ISSUE THREAD

**Issue by Xenphor** [libretro/4do-libretro#8]
I get consistent tearing in all games even with vsync enabled in retroarch. This happens on Fedora 20 64bit with Intel Mesa 10 in X or without X.

**Comment by stevenstrike** [comment]
Still not working even on Windows 8.1 (latest stable RA and 4do core to date)

**Comment by bigboo3000** [comment]
I tested with latest retroarch on windows 10 with gl and vulkan drivers and the problem still remains (tearing/ unworking vsync)

**Comment by Tasosgemah** [comment]
I never managed to make v-sync work with 4DO and i think the same issue applies for the standalone.

**Comment by altiereslima** [comment]
Still not working even

**Comment by trapexit** [comment]
The problem is 4DO itself. It's feeding bad frames to the video callback.

**Comment by trapexit** [comment]
What games have people noticed having issues?

While looking into this issue with Twisted I noticed tearing as seen in the attached screenshot. I tried using the Phoenix emulator and noticed it too has similar tearing. I plan on reaching out to the author of Phoenix to see if there would be interest in opening the project or helping provide data on the platform.

![screenshot_20180304_231254](https://user-images.githubusercontent.com/197676/36957632-ae8a85ca-2003-11e8-8a29-c1d5f29e7986.png)

**Comment by trapexit** [comment]
I may have found a way to manage some of the tearing when using Super Street Fighter 2 and Road Rash. I'll submit a pull request in the next day or two after I confirm it works across multiple titles.

**Comment by trapexit** [comment]
BTW... I reached out to the author of Phoenix and he's not interested in opening the emulator at the moment. I suppose we could offer to pay him to do so (or sell the code) but I did not go down that avenue.

**Comment by Xenphor** [comment]
I've tried using Phoenix but was not able to find an option to scale the graphics cleanly without having to use bilinear filtering. Anything else would distort the pixels.
