### ISSUE TITLE
4do libreto port android

### ISSUE THREAD

**Issue by angelhp** [libretro/4do-libretro#9]
graphical glitches in 3d Games
Need for speed for example

Can anyone add autoframeskip ?¿

**Comment by fcatrin** [comment]
I've seen that other emulators are using the same emulation engine (FreeDO), but in RetroArch the code has been ported from C++ to C, probably adding errors on it? Or do the other emulators use additional patches to run the games? Is there somebody working on this core?

**Comment by trapexit** [comment]
This should be fixed by the matrix engine change #100 

Please test and let me know.
